### ISSUE TITLE
Nitpick: Check for XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by MattSturgeon** [Etaash-mathamsetty/trigger-control#12]
Great that you're [using `$HOME/.config`](https://github.com/Etaash-mathamsetty/trigger-control/blob/53aa50920b971c1c45d918f197a62867a065ed8a/trigger-control.cpp#L372), but strictly speaking that should be a fallback for when `XDG_CONFIG_HOME` is unset.

If you want a thorough implementation you can use [this header-only library](https://sr.ht/~danyspin97/xdgpp/), or you could just do something like this:

```cpp
ifdef __linux__
    strcpy(CONFIG_PATH, getenv("XDG_CONFIG_HOME"));
    if (*CONFIG_PATH == '\0') {
        strcpy(CONFIG_PATH, getenv("HOME"));
        strcat(CONFIG_PATH, "/.config");
    }
    strcat(CONFIG_PATH, "/trigger-control/");
#endif

```

**Comment by Etaash-mathamsetty** [comment]
I was actually thinking about this, but was too lazy to implement it, but now since you asked I will add it in!

**Comment by Etaash-mathamsetty** [comment]
I fixed it with 574c7e020262aa98e6c7032176d64204053f078e (you should probably test it as well before I close this)

**Comment by MattSturgeon** [comment]
Seems to create the `trigger-control` directory in the correct place. So long as the parent directory exists, otherwise it crashes on an unhandled exception:

```
 → export XDG_CONFIG_HOME="$(pwd)/config"
 → ./trigger-control
running using wayland video driver
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directory: No such file or directory [/home/matt/Documents/Development/trigger-control/config/trigger-control/]
fish: Job 1, './trigger-control' terminated by signal SIGABRT (Abort)
 → mkdir config
 → ./trigger-control
running using wayland video driver
dpi scaling: 1.000000
```

But I'm unable to generate a `config.ini` file in either the default `~/.config/` or a set `XDG_CONFIG_HOME` - perhaps there's some other regression since `1.5B`? I'm testing by setting dark mode; no config file is created and re-launching reverts to light mode.

**Comment by Etaash-mathamsetty** [comment]
> Seems to create the `trigger-control` directory in the correct place. :+1: 
> 
> If the parent directory doesn't exists it crashes on an unhandled exception, but this would be a separate issue... If you consider it an issue at all:
> 
> ```
>  → export XDG_CONFIG_HOME="$(pwd)/config"
>  → ./trigger-control
> running using wayland video driver
> terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
>   what():  filesystem error: cannot create directory: No such file or directory [/home/matt/Documents/Development/trigger-control/config/trigger-control/]
> fish: Job 1, './trigger-control' terminated by signal SIGABRT (Abort)
>  → mkdir config
>  → ./trigger-control
> running using wayland video driver
> dpi scaling: 1.000000
> ```
> 
> But I'm unable to generate a `config.ini` file in either the default `~/.config/` or a set `XDG_CONFIG_HOME` - perhaps there's some other regression since `1.5B`?
> 
> I'm testing by setting dark mode; no config file is created and re-launching reverts to light mode.

Yeah I'll use std::filesystem to check if the path exists and I'll investigate the rest

**Comment by Etaash-mathamsetty** [comment]
closing since it's done and this issue has been inactive
