### ISSUE TITLE
Bro use releases more.

### ISSUE THREAD

**Issue by carghai** [Etaash-mathamsetty/trigger-control#15]
nothing wrong with the code just that the lack of releases is keeping people in the dark.

**Comment by Etaash-mathamsetty** [comment]
> nothing wrong with the code just that the lack of releases is keeping people in the dark.

I've just been kinda lazy lol

**Comment by carghai** [comment]
Lol

**Comment by Etaash-mathamsetty** [comment]
will make a release some time later
