### ISSUE TITLE
Pulse effects

### ISSUE THREAD

**Issue by parkerlreed** [Etaash-mathamsetty/trigger-control#17]
Are the pulse supposed to be "pulsing"? I basically get a little resistance to start but no pulsing occurs.

**Comment by Etaash-mathamsetty** [comment]
That's how it's supposed to be lol

**Comment by parkerlreed** [comment]
Oh ok. Is there an effect to simulate gunfire? That's what's I was expecting from pulse. Pulsing the motor to create feedback effects.

**Comment by Etaash-mathamsetty** [comment]
> Oh ok. Is there an effect to simulate gunfire? That's what's I was expecting from pulse. Pulsing the motor to create feedback effects.

Yeah, it is, I think you have to use PulseB and fiddle around with it

**Comment by parkerlreed** [comment]
Thanks! I'll check it out
