### ISSUE TITLE
error: No message system available

### ISSUE THREAD

**Issue by CaptainWinter** [Etaash-mathamsetty/trigger-control#18]
title.

followed all steps indicated for installation, tried the AppImage and I get the same error:
"running using x11 video driver
dpi scaling: 1.000000

error: No message system available"

I'm running endeavouros with kernel zen1 6.2.12. all required dependencies are installed and up to date

**Comment by CaptainWinter** [comment]
CI?

i also tried to compile it myself, same error

**Comment by Etaash-mathamsetty** [comment]
what DE are you using? have you installed xenity?

**Comment by CaptainWinter** [comment]
KDE, and no i havent, what is it?

**Comment by Etaash-mathamsetty** [comment]
> KDE, and no i havent, what is it?

a modal system

**Comment by CaptainWinter** [comment]
just checked, zenity was already installed

**Comment by Etaash-mathamsetty** [comment]
> just checked, zenity was already installed

is kdialog installed as well?

**Comment by CaptainWinter** [comment]
it solved it, i was missing kdialog, thanks!
