### ISSUE TITLE
Error while loading shared libraries: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ThatCataLysT** [Etaash-mathamsetty/trigger-control#20]
Title. I'm running Nobara 37, which is based on Fedora. My guess is that the package that it's looking for is named differently in the Fedora repos (SDL2_mixer instead of libSDL2_mixer)

**Comment by Etaash-mathamsetty** [comment]
This is a bug with the app image I fixed a long time ago, but haven't made a new release
