### ISSUE TITLE
So, how exactly is this working on linux?

### ISSUE THREAD

**Issue by Bitwolfies** [Etaash-mathamsetty/trigger-control#8]
Not so much an issue, but a question, my apologies in advance. 

As far as I can tell, the Linux Dualsense driver, both wired and wireless lack support for anything related to the triggers, so how is this managing it? Even Windows can't use the triggers wirelesly, is it more of a replacement driver than anything else?

Thanks!

**Comment by Etaash-mathamsetty** [comment]
> Not so much an issue, but a question, my apologies in advance.
> 
> As far as I can tell, the Linux Dualsense driver, both wired and wireless lack support for anything related to the triggers, so how is this managing it? Even Windows can't use the triggers wirelesly, is it more of a replacement driver than anything else?
> 
> Thanks!

there is no official driver for this (I wish there was, it is so simple to add it :/), so we have to send raw HID data to the device to control the triggers. SDL2 handles this well (with bluetooth support), and so I just use SDL2's gamecontroller api to send raw HID commands to the controller. In essense it's 100% userspace and there is no kernel level driver or anything else involved. (you can obviously look at the source code for more details)

**Comment by Bitwolfies** [comment]
> > Not so much an issue, but a question, my apologies in advance.
> > As far as I can tell, the Linux Dualsense driver, both wired and wireless lack support for anything related to the triggers, so how is this managing it? Even Windows can't use the triggers wirelesly, is it more of a replacement driver than anything else?
> > Thanks!
> 
> there is no official driver for this (I wish there was, it is so simple to add it :/), so we have to send raw HID data to the device to control the triggers. SDL2 handles this well (with bluetooth support), and so I just use SDL2's gamecontroller api to send raw HID commands to the controller. In essense it's 100% userspace and there is no kernel level driver or anything else involved. (you can obviously look at the source code for more details)

So how come there's zero effort to upstream this. not wanting to step on Sony's toes? I know the dev from sony said that endev was not sufficient to expose these values.

**Comment by Etaash-mathamsetty** [comment]
> > > Not so much an issue, but a question, my apologies in advance.
> > > As far as I can tell, the Linux Dualsense driver, both wired and wireless lack support for anything related to the triggers, so how is this managing it? Even Windows can't use the triggers wirelesly, is it more of a replacement driver than anything else?
> > > Thanks!
> > 
> > 
> > there is no official driver for this (I wish there was, it is so simple to add it :/), so we have to send raw HID data to the device to control the triggers. SDL2 handles this well (with bluetooth support), and so I just use SDL2's gamecontroller api to send raw HID commands to the controller. In essense it's 100% userspace and there is no kernel level driver or anything else involved. (you can obviously look at the source code for more details)
> 
> So how come there's zero effort to upstream this. not wanting to step on Sony's toes? I know the dev from sony said that endev was not sufficient to expose these values.

I really don't want to dip my toes in kernel development just yet, I really have no idea how to contribute or do anything in there. I might work on this as a kernel module in the future and upstream it, but there is still no guarantee that linus upstreams it, and weither it is a good interface for controlling the triggers in the first place.

**Comment by Etaash-mathamsetty** [comment]
If you have any further questions, you can move it over to the discussions page
